# 
# this is a java project using maven
language: java

# switch off gpg handling
# and split install and test phase of maven since xvfb will only
# be available in test phase
# let's first compile without tests
install: mvn install -DskipTests=true -Dgpg.skip=true
# do the tests separately 
script: mvn test
