# 
# this is a java project using maven
language: 
  java

# switch off gpg handling
# and split install and test phase of maven since xvfb will only
# be available in test phase
# let's first compile without tests
install: 
  # get the Railroad Diagrams for ANTLR 4 grammar rules. 
  - cd ..;git clone https://github.com/bkiers/rrd-antlr4
  # make it locally available
  - cd ../rrd-antlr4;mvn clean package
  # then install the local com.bitplan.antlr 
  - mvn install -DskipTests=true -Dgpg.skip=true

# do the tests separately 
script: 
  mvn test
